site_name: image-uploader-widget
site_url: https://inventare.github.io/django-image-uploader-widget
repo_url: https://github.com/inventare/django-image-uploader-widget
repo_name: inventare/django-image-uploader-widget

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  icon:
    repo: fontawesome/brands/github
    logo: material/image
  favicon: _images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - _stylesheets/extra.css

plugins:
  - glightbox
  - awesome-pages
  - search

extra:
  homepage: https://inventare.github.io/django-image-uploader-widget/

nav:
  - index.md
  - Widget:
    - ... | flat | widget/*.md
    - Specific Cases:
      - ... | flat | widget/specific-cases/*.md
  - ArrayField:
    - ... | flat | array_field/*.md
  - HTMX:
    - ... | flat | htmx/*.md
  - Inline Admin:
    - ... | flat | inline_admin/*.md
  - Development:
    - ... | flat | development/*.md
    - Architecture Decision Records:
      - ... | flat | development/architecture-decision-records/*.md
